version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
  - dependency-name: setuptools
  - dependency-name: twine
  - dependency-name: wheel
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
